services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  Kussin\OxidAssetCleanup\Service\:
    resource: './src/Service/'

  Kussin\OxidAssetCleanup\Command\ScanMasterPicturesCommand:
    tags:
      - { name: 'console.command', command: 'kussin:asset-cleanup:scan-master' }

  Kussin\OxidAssetCleanup\Command\DeleteMasterPicturesCommand:
    tags:
      - { name: 'console.command', command: 'kussin:asset-cleanup:delete-master' }

  Kussin\OxidAssetCleanup\Command\DeleteFatchipWebpCommand:
    tags:
      - { name: 'console.command', command: 'kussin:asset-cleanup:delete-fcwebp' }
