services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  Kussin\OxidAssetCleanup\Service\:
    resource: './src/Service/'

  Kussin\OxidAssetCleanup\Command\ScanMasterPicturesCommand:
    tags:
      - { name: 'console.command', command: 'kussin:asset-cleanup:scan-master' }

  Kussin\OxidAssetCleanup\Command\DeleteMasterPicturesCommand:
    tags:
      - { name: 'console.command', command: 'kussin:asset-cleanup:delete-master' }

  Kussin\OxidAssetCleanup\Command\DeleteFatchipWebpCommand:
    tags:
      - { name: 'console.command', command: 'kussin:asset-cleanup:delete-fcwebp' }

  Kussin\OxidAssetCleanup\Command\FlushImageCacheCommand:
    tags:
      - { name: 'console.command', command: 'kussin:asset-cleanup:flush-image-cache' }

  Kussin\OxidAssetCleanup\Command\StatusCommand:
    tags:
      - { name: 'console.command', command: 'kussin:asset-cleanup:status' }

  Kussin\OxidAssetCleanup\Command\DeleteDuplicateDirectoryFilesCommand:
    tags:
      - { name: 'console.command', command: 'kussin:asset-cleanup:delete-duplicate-directory-files' }
